[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[cursor]
style = "Block"
blink_interval=150

[window]
opacity = 0.9

# github Alacritty Colors

# Default colors
[colors.primary]
background = '#24292e'
foreground = '#d1d5da'

# Normal colors
[colors.normal]
black   = '#586069'
red     = '#ea4a5a'
green   = '#34d058'
yellow  = '#ffea7f'
blue    = '#2188ff'
magenta = '#b392f0'
cyan    = '#39c5cf'
white   = '#d1d5da'

# Bright colors
[colors.bright]
black   = '#959da5'
red     = '#f97583'
green   = '#85e89d'
yellow  = '#ffea7f'
blue    = '#79b8ff'
magenta = '#b392f0'
cyan    = '#56d4dd'
white   = '#fafbfc'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#f97583'
# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
# [colors.primary]
# background = '#000000'
# foreground = '#a9b1d6'

# [general]
# import = [
#     "~/.config/alacritty/themes/themes/github_dark.toml"
# ]
# Normal colors
# [colors.normal]
# black   = '#32344a'
# red     = '#f7768e'
# green   = '#9ece6a'
# yellow  = '#e0af68'
# blue    = '#7aa2f7'
# magenta = '#ad8ee6'
# cyan    = '#449dab'
# white   = '#787c99'
#
# # Bright colors
# [colors.bright]
# black   = '#444b6a'
# red     = '#ff7a93'
# green   = '#b9f27c'
# yellow  = '#ff9e64'
# blue    = '#7da6ff'
# magenta = '#bb9af7'
# cyan    = '#0db9d7'
# white   = '#acb0d0'
# # Colors (Alabaster Dark)
# # author tonsky
#
# [colors.primary]
# background = '#000000'
# foreground = '#CECECE'
#
# [colors.cursor]
# text = '#0E1415'
# cursor = '#CECECE'
#
# [colors.normal]
# black = '#0E1415'
# red = '#e25d56'
# green = '#73ca50'
# yellow = '#e9bf57'
# blue = '#4a88e4'
# magenta = '#915caf'
# cyan = '#23acdd'
# white = '#f0f0f0'
#
# # [colors.bright]
# # black = '#777777'
# # red = '#f36868'
# # green = '#88db3f'
# # yellow = '#f0bf7a'
# # blue = '#6f8fdb'
# # magenta = '#e987e9'
# # cyan = '#4ac9e2'
# # white = '#FFFFFF'
# scheme: "Black Metal (Bathory)"
# author: "metalelf0 (https://github.com/metalelf0)"
# base00: "#000000"
# base01: "#121212"
# base02: "#222222"
# base03: "#333333"
# base04: "#999999"
# base05: "#c1c1c1"
# base06: "#999999"
# base07: "#c1c1c1"
# base08: "#5f8787"
# base09: "#aaaaaa"
# base0A: "#e78a53"
# base0B: "#fbcb97"
# base0C: "#aaaaaa"
# base0D: "#888888"
# base0E: "#999999"
# base0F: "#444444"
