# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131413)
$foreground = rgb(E9EAEB)
$color0 = rgb(3B3C3B)
$color1 = rgb(72716D)
$color2 = rgb(919394)
$color3 = rgb(919394)
$color4 = rgb(919394)
$color5 = rgb(919394)
$color6 = rgb(919394)
$color7 = rgb(D8D9DA)
$color8 = rgb(979899)
$color9 = rgb(989792)
$color10 = rgb(C1C4C6)
$color11 = rgb(C1C4C6)
$color12 = rgb(C1C4C6)
$color13 = rgb(C1C4C6)
$color14 = rgb(C1C4C6)
$color15 = rgb(D8D9DA)
