set-option -g status-position bottom 
# set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # colored underscores
set -g status-right '#[fg=color249]#(date +"%I:%M%p %m-%d-%Y")#[default]'
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# set -as terminal-overrides ',alacritty:RGB' # true-color support
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'jimeh/tmux-themepack'
# set -g @plugin 'shaneog/tmux-colors-gotham'
# set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g mouse on
# set -g @themepack 'basic'
# Other examples:
# set -g @plugin 'shaneog/tmux-colors-gotham'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
#### COLOUR (Gotham)

# colors
set-option -g status-bg "#333333"
set-option -g status-fg "#5eacd3"
set -g mode-style "fg=black,bg=#8a8987"
set -g pane-active-border-style 'fg=#8a8987'
set -g pane-border-style 'fg=#8a8987'
# copy mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

set -g allow-passthrough on
set -g default-terminal "tmux-256color"
set -as terminal-features ',xterm-kitty:RGB'

